CREATE TABLE IF NOT EXISTS static_data (
  data_key   VARCHAR(50)  NOT NULL PRIMARY KEY,
  data_json  JSON         NOT NULL,
  updated_at DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
