Args = --initialize-at-run-time=com.mysql.cj \
       --initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread \
       --initialize-at-run-time=com.github.benmanes.caffeine \
       -H:EnableURLProtocols=http,https
